### PR TITLE
Move to python package format, allow lookup from (s3) remote state, add user choice for aws keys

### PR DESCRIPTION
**Pull request by sean-abbott**
Now that I've left the testing in approximately equal to it's previous state, I'm ready to request a merge.

Some things to note:

`py.test` is how I've been testing this.  You'll need/want to `pip install -e .[test]` before trying to run the tests.

I updated the readme with new usage instructions, but this is a breaking change from previous versions, so please let me know if you don't understand the new usage.

The hypothesis tests are slow, but I think property based testing makes sense.  Maybe we could mark slow tests, and run other tests first, then slow tests?

I look forward to your feedback!

### CODE REVIEW

**Comment by sean-abbott** [comment]
Re-commenting in the hopes that I will get a second pair of eyes on this before we merge (and I don't believe I should merge it myself, because that's bad karma).

I would love for someone to confirm that it works for them in an environment that they've been using terraform.py. Please make sure you check out the updated use instructions in the README.

**Comment by pat2man** [comment]
Gave it a shot in our environment, no issues!

**Comment by Theaxiom** [comment]
Thank you for the feedback @pat2man !

**Comment by Theaxiom** [comment]
@sean-abbott Needs to be rebased first, then you can merge it in.

**Pull request merged**
