### PR TITLE
Azurerm support

### PR DESCRIPTION
**Pull request by broomyocymru**
Adding AzureRM support

### CODE REVIEW

**Comment by rossedman** [comment]
@broomyocymru Awesome! This is great. 👍

**Comment by broomyocymru** [comment]
Anything else required to get it merged?

**Comment by rossedman** [comment]
Hey @BrianHicks can we get this merged? Tests are added and passing.

**Comment by BrianHicks** [comment]
@rossedman I'm an external contributor and while I technically could merge this, I no longer have the authority to do so.

@cnguyen2, could you please route @rossedman's request to the appropriate party within Cisco?

**Comment by rossedman** [comment]
@BrianHicks ah thanks, I didn't realize you didn't have that authority any more. Thanks a lot. Will ping @cnguyen2 to understand process more.

**Pull request merged**
