### PR TITLE
Added test whether unicode is known, see issue 74 for details

### PR DESCRIPTION
**Pull request by mjuenema**
Hi, i had an attempt at solving issue #74. I am happy to change the code if you prefer a different solution.

### CODE REVIEW

**Comment by mjuenema** [comment]
I understand this has also been addressed in pull request 66 in an alternative approach.

**Comment by kmoe** [comment]
Thanks for closing https://github.com/mantl/terraform.py/pull/75 @Cryptophobia! Please could you also merge this PR (once conflicts are resolved by @mjuenema) so `terraform.py` works with python 3?

**Comment by Cryptophobia** [comment]
Sure, @mjuenema do you want to resolve this so I can get it merged?

**Comment by Cryptophobia** [comment]
@kmoe , this was merged in today and it should work with python 3.

**Comment by Theaxiom** [comment]
We also have automated builds of every branch, so you can point to phusion/baseimage-docker:master etc

**Pull request merged**
