### PR TITLE
Pr scalway integration

### PR DESCRIPTION
**Pull request by sagagliardo**

### CODE REVIEW

**Comment by thomasvincent** [comment]
Will merge into the Int branch

**Comment by sagagliardo** [comment]
Awesome. Thanks.

**Comment by Theaxiom** [comment]
This is breaking the Travis build.

**Comment by sagagliardo** [comment]
Trying to. Thanks.

**Comment by sagagliardo** [comment]
Will work on this more during the evening and get this resolved.

**Comment by Theaxiom** [comment]
Thank you @sagagliardo :)

**Comment by sagagliardo** [comment]
@Theaxiom Looking better now.

**Pull request merged**
